name: Python application

on:
  push:
    branches:
      - main  # Trigger the workflow only on push to main branch
  pull_request:
    branches:
      - main  # Trigger the workflow when a pull request targets the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the code from your repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Set the Python version to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install the dependencies from requirements.txt

    - name: Run tests
      run: |
        pytest  # Run tests using pytest
